import PrimeFactorUnimodality.Helpers.Analytic.FinitePrimeIntervalRows.ShortIntervalSieveRows

set_option autoImplicit false
set_option maxRecDepth 100000

/-! # Shared short-interval sieve

Generated by `scripts/generate_dusart_published_short_prefix.py`.
Semantic SHA-256: 0bc33166d15dc50b4cfaf567d22ffbe810893931e1f32d10811629333155e5fc
Strict prime endpoints are included in the following cell.
-/

namespace PrimeFactorUnimodality.DusartPublishedShortPrefix

noncomputable def sieve : Nat := PrimeCert.Sieve.sieveK 4000000 2000

theorem sieve_valid : PrimeCert.Sieve.IsSieve 4000000 sieve :=
  PrimeCert.Sieve.isSieve_of_sieveK_eq
    (show PrimeCert.Sieve.sieveK 4000000 2000 = sieve from rfl)
    (by decide) (by decide)

end PrimeFactorUnimodality.DusartPublishedShortPrefix
