import PrimeFactorUnimodality.Helpers.Analytic.FinitePrimeIntervalRows.PrimeCountingSieveRows

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 0

/-! # Shared published-cutoff sieve

Generated by `scripts/generate_dusart_published_pi_prefix.py`.
Semantic SHA-256: f5ffd585723ab3d44b013960bce5ef9c62e41e16c18c51821e22f3bb6d157fe0
Half-open cells retain prime jumps at their left endpoints.
-/

namespace PrimeFactorUnimodality.DusartPublishedPiPrefix

noncomputable def sieve : Nat := PrimeCert.Sieve.sieveK 3594641 1896

theorem sieve_valid : PrimeCert.Sieve.IsSieve 3594641 sieve :=
  PrimeCert.Sieve.isSieve_of_sieveK_eq
    (show PrimeCert.Sieve.sieveK 3594641 1896 = sieve from rfl) (by decide) (by decide)

end PrimeFactorUnimodality.DusartPublishedPiPrefix
