import PrimeFactorUnimodality.Helpers.Analytic.FinitePrimeIntervalRows.ThetaSieveTrace

set_option autoImplicit false
set_option maxRecDepth 100000

/-! # Shared theta-prefix sieve

Generated by `scripts/generate_dusart_tail_theta_prefix.py`.
Semantic SHA-256: 801233ff18cf51ee099ba33025c464f6ffdd6cad684298c9dcf5c72c26dd6f32
Only the data in this replay unit contributes to its semantic digest.
-/

namespace PrimeFactorUnimodality.DusartTailThetaPrefix

noncomputable def sieve : Nat := PrimeCert.Sieve.sieveK 3594641 1896

theorem sieve_valid : PrimeCert.Sieve.IsSieve 3594641 sieve :=
  PrimeCert.Sieve.isSieve_of_sieveK_eq
    (show PrimeCert.Sieve.sieveK 3594641 1896 = sieve from rfl)
    (by decide) (by decide)

end PrimeFactorUnimodality.DusartTailThetaPrefix
