import PrimeFactorUnimodality.Helpers.Analytic.DusartPrimeCountingClosed
import PrimeFactorUnimodality.Helpers.FiniteCertificates.DusartPublishedPiPrefix.Part09

/-! # Closed prime-counting prefix through the published Dusart cutoff

Generated by `scripts/generate_dusart_published_pi_prefix.py`.
Semantic SHA-256: f5ffd585723ab3d44b013960bce5ef9c62e41e16c18c51821e22f3bb6d157fe0
The small closed prefix and half-open extension include every real input
through 3,594,641, not just integer sample points.
-/

namespace PrimeFactorUnimodality

theorem dusart_published_primeCountingPrefix :
    HasDusartRealPrimeCountingBoundsBelow 3594641 :=
  hasDusartRealPrimeCountingBoundsBelow_of_halfOpen wangCrapis_primeCountingPrefix
    DusartPublishedPiPrefix.throughPart09

end PrimeFactorUnimodality
