import PrimeFactorUnimodality.Helpers.Analytic.FinitePrimeIntervalRows.PrimeCountingCertificates

set_option autoImplicit false
set_option maxRecDepth 10000

/-! # Shared prime-counting prefix certificate

Generated by `scripts/generate_dusart_pi_prefix.py`.
Semantic SHA-256: 5e6fac35ccddeca19c0d0610bb6e8e1100344cd320692c5a18c4fc5d84f1b733
One prime list supplies all 33 rational endpoint rows.
-/

namespace PrimeFactorUnimodality

def dusartPrimesThrough1000 : List Nat :=
  [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37,
    41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89,
    97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151,
    157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223,
    227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281,
    283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359,
    367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433,
    439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503,
    509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593,
    599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659,
    661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743,
    751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827,
    829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911,
    919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]

theorem dusartPrimesThrough1000_eq :
    computablePrimesBelow 1001 = dusartPrimesThrough1000 := by
  decide +kernel

theorem dusart_primeCounting_eq_filtered_1000 {n : Nat} (hn : n ≤ 1000) :
    Nat.primeCounting n = dusartPrefixCount dusartPrimesThrough1000 n :=
  primeCounting_eq_filter_length_of_prime_prefix hn dusartPrimesThrough1000_eq

def dusartPrimeCountingCertificateRows599_1000 : List DusartPrimeCountingCertificateRow :=
  [⟨599, 603, ⟨8, 12, 20, 13⟩, ⟨8, 28, 4, 17⟩⟩,
    ⟨603, 610, ⟨8, 40, 20, 1⟩, ⟨8, 20, 34, 0⟩⟩,
    ⟨610, 617, ⟨8, 22, 8, 17⟩, ⟨8, 25, 28, 2⟩⟩,
    ⟨617, 630, ⟨8, 18, 18, 12⟩, ⟨8, 6, 43, 0⟩⟩,
    ⟨630, 637, ⟨8, 29, 17, 8⟩, ⟨8, 3, 26, 13⟩⟩,
    ⟨637, 644, ⟨8, 40, 16, 4⟩, ⟨8, 14, 25, 9⟩⟩,
    ⟨644, 657, ⟨8, 19, 25, 7⟩, ⟨8, 25, 24, 5⟩⟩,
    ⟨657, 671, ⟨8, 39, 14, 6⟩, ⟨8, 4, 33, 8⟩⟩,
    ⟨671, 682, ⟨8, 32, 20, 5⟩, ⟨8, 24, 22, 7⟩⟩,
    ⟨682, 690, ⟨8, 37, 14, 7⟩, ⟨8, 17, 28, 6⟩⟩,
    ⟨690, 705, ⟨8, 12, 27, 9⟩, ⟨8, 22, 22, 8⟩⟩,
    ⟨705, 719, ⟨8, 21, 20, 10⟩, ⟨8, 13, 0, 27⟩⟩,
    ⟨719, 733, ⟨8, 21, 26, 6⟩, ⟨8, 6, 28, 11⟩⟩,
    ⟨733, 747, ⟨8, 51, 16, 0⟩, ⟨8, 6, 34, 7⟩⟩,
    ⟨747, 760, ⟨8, 9, 6, 25⟩, ⟨8, 36, 24, 1⟩⟩,
    ⟨760, 772, ⟨8, 8, 17, 18⟩, ⟨8, 47, 4, 10⟩⟩,
    ⟨772, 788, ⟨8, 34, 11, 11⟩, ⟨8, 46, 15, 3⟩⟩,
    ⟨788, 802, ⟨8, 0, 15, 23⟩, ⟨8, 19, 19, 12⟩⟩,
    ⟨802, 809, ⟨8, 36, 7, 13⟩, ⟨8, 38, 13, 8⟩⟩,
    ⟨809, 816, ⟨8, 33, 28, 0⟩, ⟨8, 21, 15, 14⟩⟩,
    ⟨816, 823, ⟨8, 46, 14, 4⟩, ⟨8, 34, 1, 18⟩⟩,
    ⟨823, 838, ⟨8, 5, 40, 4⟩, ⟨8, 31, 22, 5⟩⟩,
    ⟨838, 852, ⟨8, 22, 25, 7⟩, ⟨8, 59, 3, 6⟩⟩,
    ⟨852, 859, ⟨8, 26, 24, 6⟩, ⟨8, 7, 33, 8⟩⟩,
    ⟨859, 880, ⟨8, 38, 21, 3⟩, ⟨8, 11, 32, 7⟩⟩,
    ⟨880, 894, ⟨8, 38, 5, 14⟩, ⟨8, 23, 29, 4⟩⟩,
    ⟨894, 915, ⟨8, 32, 28, 1⟩, ⟨8, 23, 13, 15⟩⟩,
    ⟨915, 930, ⟨8, 3, 1, 32⟩, ⟨8, 33, 1, 19⟩⟩,
    ⟨930, 944, ⟨8, 8, 17, 19⟩, ⟨8, 25, 34, 0⟩⟩,
    ⟨944, 958, ⟨8, 5, 19, 19⟩, ⟨8, 46, 15, 4⟩⟩,
    ⟨958, 973, ⟨8, 34, 14, 10⟩, ⟨8, 43, 17, 4⟩⟩,
    ⟨973, 987, ⟨8, 7, 37, 6⟩, ⟨8, 19, 22, 11⟩⟩,
    ⟨987, 1000, ⟨8, 24, 0, 24⟩, ⟨8, 61, 0, 8⟩⟩]

private theorem certificate_valid :
    dusartPrimeCountingCertificateRows599_1000.all
      (fun row => row.check 1000 dusartPrimesThrough1000) = true := by
  decide +kernel

private theorem certificate_chain :
    dusartThetaTable66CellsChain 599 1000
      (dusartPrimeCountingCertificateRows599_1000.map
        DusartPrimeCountingCertificateRow.coverageCell) = true := by
  decide +kernel

theorem dusartPrimeCounting_599_1000 :
    ∀ x : Real, 599 ≤ x → x ≤ 1000 →
      dusartPiLower x ≤ (Nat.primeCounting ⌊x⌋₊ : Real) ∧
        (Nat.primeCounting ⌊x⌋₊ : Real) ≤ dusartPiUpper x :=
  dusartPrimeCountingCertificateRows_provide dusartPrimesThrough1000_eq
    dusartPrimeCountingCertificateRows599_1000 certificate_valid certificate_chain

end PrimeFactorUnimodality
