import PrimeFactorUnimodality.Helpers.FiniteCertificates.DusartTailThetaPrefix.Part26

/-! # Closed finite theta prefix for the all-k tail

Generated by `scripts/generate_dusart_tail_theta_prefix.py`.
Semantic SHA-256: 71eaeed047c8df90d1b290d2372a8d19e36c67d9644d1c5d7d5b9f5e3de8e191
All endpoint counts, accumulated logarithm sums and strict margins are checked.
-/

namespace PrimeFactorUnimodality

theorem dusart_tail_theta_prefix (q : Nat) (hq : 3501 ≤ q) (hcut : q < 3594641) :
    TailThetaAt q :=
  DusartTailThetaPrefix.throughPart26 q hq (by omega) hcut

end PrimeFactorUnimodality
