import PrimeFactorUnimodality.Helpers.FiniteCertificates.DusartPublishedShortPrefix.Part08

/-! # Closed short-interval prefix through the published Dusart cutoff

Generated by `scripts/generate_dusart_published_short_prefix.py`.
Semantic SHA-256: 0bc33166d15dc50b4cfaf567d22ffbe810893931e1f32d10811629333155e5fc
The half-open cover includes every real input through 3,594,641.
-/

namespace PrimeFactorUnimodality

theorem dusart_published_shortIntervalPrefix :
    HasDusartShortIntervalPrimeBelow 3594641 :=
  hasDusartShortIntervalPrimeBelow_of_halfOpen (by decide : 3594641 < 3601993)
    DusartPublishedShortPrefix.throughPart08

end PrimeFactorUnimodality
