import Mathlib.Algebra.BigOperators.Field
import PrimeFactorUnimodality.Mathlib.Analysis.SpecialFunctions.Trigonometric.Autocorrelation

/-! # Exact polynomial generated by the published degree-sixteen sequence

Mossinghoff--Trudgian, "Nonnegative Trigonometric Polynomials and a Zero-Free
Region for the Riemann Zeta-Function", arXiv:1410.3926, section 5 and table 5,
construct the cosine coefficients by autocorrelation of a real sequence.
Here the displayed generating decimals are exact rationals. We recompute
the cosine coefficients from them instead of assuming that the separately
rounded columns of the table satisfy an exact identity.

Global phase nonnegativity follows symbolically from a sum of squares.
Coefficient signs and the final numerical zero-free-region margin are
separate obligations: neither follows from nonnegativity of the polynomial.
-/

namespace PrimeFactorUnimodality

noncomputable section

open Finset Real

/-- Exact rational values of the generating sequence displayed in table 5. -/
def mossinghoffTrudgianGeneratorRat : ℕ → ℚ
  | 0 => 1
  | 1 => -2.09100370089199
  | 2 => 0.414661861733616
  | 3 => 4.94973437766435
  | 4 => -2.26052224951171
  | 5 => -8.58599241204357
  | 6 => 6.87053689828658
  | 7 => 22.6412990090005
  | 8 => -6.76222005424994
  | 9 => -50.2233943767588
  | 10 => 8.07550113395201
  | 11 => 223.771572768515
  | 12 => 487.278135806977
  | 13 => 597.268928658734
  | 14 => 473.937203439807
  | 15 => 237.271715181426
  | 16 => 59.6961898512813
  | _ => 0

/-- The real generating sequence is the cast of the single exact rational table. -/
def mossinghoffTrudgianGenerator (j : ℕ) : ℝ := mossinghoffTrudgianGeneratorRat j

/-- The positive normalization making the zero cosine coefficient equal to one. -/
def mossinghoffTrudgianEnergy : ℝ :=
  ∑ j ∈ range 17, mossinghoffTrudgianGenerator j ^ 2

/-- Autocorrelation coefficients, recomputed exactly from the generating sequence. -/
def mossinghoffTrudgianCoefficient (k : ℕ) : ℝ :=
  cosineAutocorrelationCoeff (range 17) mossinghoffTrudgianGenerator k /
    mossinghoffTrudgianEnergy

/-- The first generating coefficient already gives a strictly positive normalization. -/
theorem mossinghoffTrudgianEnergy_pos : 0 < mossinghoffTrudgianEnergy := by
  have h := single_le_sum (fun j (_ : j ∈ range 17) =>
    sq_nonneg (mossinghoffTrudgianGenerator j)) (show 0 ∈ range 17 by decide)
  have hfirst : mossinghoffTrudgianGenerator 0 ^ 2 = 1 := by
    norm_num [mossinghoffTrudgianGenerator, mossinghoffTrudgianGeneratorRat]
  rw [hfirst] at h
  exact lt_of_lt_of_le (by norm_num : (0 : ℝ) < 1) h

/-- The normalized polynomial has constant cosine coefficient exactly one. -/
@[simp]
theorem mossinghoffTrudgianCoefficient_zero : mossinghoffTrudgianCoefficient 0 = 1 := by
  simp only [mossinghoffTrudgianCoefficient, cosineAutocorrelationCoeff_zero]
  exact div_self mossinghoffTrudgianEnergy_pos.ne'

/-- Positive-frequency coefficients use only one linear-sized correlation row. -/
theorem mossinghoffTrudgianCoefficient_pos_frequency {k : ℕ} (hk : 0 < k) :
    mossinghoffTrudgianCoefficient k =
      (2 * ∑ j ∈ range (17 - k), mossinghoffTrudgianGenerator j *
        mossinghoffTrudgianGenerator (j + k)) / mossinghoffTrudgianEnergy := by
  rw [mossinghoffTrudgianCoefficient, cosineAutocorrelationCoeff_range_pos 17 _ hk]

/-- The exact polynomial is nonnegative for every real phase, not just sampled phases. -/
theorem mossinghoffTrudgianPolynomial_nonneg (u : ℝ) :
    0 ≤ ∑ k ∈ range 17, mossinghoffTrudgianCoefficient k * cos ((k : ℝ) * u) := by
  simp only [mossinghoffTrudgianCoefficient, div_mul_eq_mul_div, ← sum_div]
  exact div_nonneg
    (sum_cosineAutocorrelationCoeff_mul_cos_nonneg (range 17) mossinghoffTrudgianGenerator
      16 (by intro i hi; simp only [mem_range] at hi; omega) u)
    mossinghoffTrudgianEnergy_pos.le

/-- The total coefficient mass is obtained from the generating sequence without trigonometry. -/
theorem sum_mossinghoffTrudgianCoefficient :
    (∑ k ∈ range 17, mossinghoffTrudgianCoefficient k) =
      (∑ j ∈ range 17, mossinghoffTrudgianGenerator j) ^ 2 / mossinghoffTrudgianEnergy := by
  simp only [mossinghoffTrudgianCoefficient, ← sum_div]
  rw [sum_cosineAutocorrelationCoeff (range 17) mossinghoffTrudgianGenerator 16
    (by intro i hi; simp only [mem_range] at hi; omega)]

end

end PrimeFactorUnimodality
