"""Bounded, positional factor rows and shared Lean certificate assemblers."""

from __future__ import annotations

from dataclasses import dataclass
from itertools import pairwise

MODULE = "PrimeFactorUnimodality.Proof.LargeRange"
GENERATED = f"{MODULE}.Generated.FullRecordGapCompactRows"
ROW_SIZE = 4096
ROWS_PER_SHARD = 2


@dataclass(frozen=True)
class Row:
    side: str
    start: int
    factors: tuple[int, ...]
    number: int

    @property
    def stop(self) -> int:
        return self.start + len(self.factors)

    @property
    def tag(self) -> str:
        return f"{self.number:03d}"

    @property
    def add(self) -> str:
        return "true" if self.side == "Add" else "false"


def make_rows(side: str, factors: list[int], first: int) -> list[Row]:
    if side not in {"Sub", "Add"} or not factors or any(q < 0 or q == 1 for q in factors):
        raise ValueError("invalid factor-row domain")
    return [
        Row(side, start + 1, tuple(factors[start : start + ROW_SIZE]), first + index)
        for index, start in enumerate(range(0, len(factors), ROW_SIZE))
    ]


def header(imports: list[str], title: str, *, modular: bool = True) -> str:
    directive = "public import" if modular else "import"
    prefix = "module\n" if modular else ""
    section = "public section\n" if modular else ""
    return (
        prefix
        + "\n".join(f"{directive} {name}" for name in sorted(imports))
        + f"""

/-! # {title}

Generated by `scripts/render_full_record_gap_compact.py`; edit the generator.
Factor positions are offsets, and zero entries require Fermat certificates.
-/

set_option autoImplicit false
set_option maxRecDepth 100000

{section}
namespace PrimeFactorUnimodality

"""
    )


def render_owners(row: Row) -> str:
    imports = [f"{MODULE}.CompactGapCertificate"]
    if row.number > 1:
        imports.append(f"{GENERATED}.Owners{row.number - 1:03d}")
    lines = [
        ", ".join(str(q) for q in row.factors[start : start + 24])
        for start in range(0, len(row.factors), 24)
    ]
    data = ",\n    ".join(lines)
    return (
        header(imports, f"Explicit factor row {row.tag}")
        + f"""@[expose] def compactGapFactors{row.tag} : List Nat :=
  [ {data} ]

set_option maxHeartbeats 0 in
-- The row has a fixed size, independently of the global gap length.
theorem compactGapOwners{row.tag} :
    compactGapCheck {row.add} {row.start} compactGapFactors{row.tag} = true := by
  eager_decide

end PrimeFactorUnimodality
"""
    )


def render_replay(row: Row, previous: Row | None) -> str:
    imports = [f"{MODULE}.CompactGapReplay", f"{GENERATED}.Owners{row.tag}"]
    if previous is not None:
        imports.append(f"{GENERATED}.Replay{previous.tag}")
    return (
        header(imports, f"Bounded exception replay {row.tag}")
        + f"""set_option maxHeartbeats 0 in
-- Each modular-power checkpoint has a fixed binary-window bound.
theorem compactGapExceptions{row.tag} :
    CompactGapComposites
      (compactGapExceptions {row.add} {row.start} compactGapFactors{row.tag}) := by
  replay_gap_fermat

theorem compactGapBlock{row.tag} : CompactGapBlock {row.add} {row.start} {row.stop} :=
  compactGapCheck_sound {row.add} {row.start} compactGapFactors{row.tag}
    compactGapOwners{row.tag} compactGapExceptions{row.tag}

end PrimeFactorUnimodality
"""
    )


def render_aggregate(rows: list[Row], terminals: list[str]) -> str:
    imports = [*terminals, f"{MODULE}.Generated.FullRecordGapCenter"]
    lines = [header(imports, "Full record-gap assembly from bounded rows", modular=False)]
    for side, bound in (("Sub", 455704), ("Add", 657402)):
        selected = [row for row in rows if row.side == side]
        if not selected or selected[0].start != 1 or selected[-1].stop != bound:
            raise ValueError(f"incomplete {side} coverage")
        for left, right in pairwise(selected):
            if left.stop != right.start:
                raise ValueError("row gap or overlap")
        previous = f"compactGapThrough{selected[-1].tag}"
        operator = "+" if side == "Add" else "-"
        lines.append(
            f"theorem fullRecordGap{side}Block (d : Nat) (hd : 1 ≤ d)\n"
            f"    (hu : d ≤ {bound - 1}) : ¬ (recordGapCenter {operator} d).Prime := by\n"
            f"  have h := {previous} d hd (by omega)\n"
            "  simpa only [compactGapNumber, recordGapCenter_eq_fullRecordGapCenterValue,\n"
            "    Bool.false_eq_true, ↓reduceIte] using h\n"
        )
    lines.append("end PrimeFactorUnimodality\n")
    return "\n".join(lines)


def render_assembly(rows: list[Row], number: int) -> str:
    imports = [f"{GENERATED}.Replay{row.tag}" for row in rows]
    if number > 1:
        imports.append(f"{GENERATED}.Assembly{number - 1:03d}")
    lines = [header(imports, f"Record-gap assembly group {number}")]
    for row in rows:
        proof = f"compactGapBlock{row.tag}"
        if row.start != 1:
            proof = f"compactGapBlock_append compactGapThrough{row.number - 1:03d} {proof}"
        lines.append(
            f"theorem compactGapThrough{row.tag} : CompactGapBlock {row.add} 1 {row.stop} :=\n"
            f"  {proof}\n"
        )
    lines.append("end PrimeFactorUnimodality\n")
    return "\n".join(lines)
