"""Generate compact half-open prime-count bounds through Dusart's published cutoff."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from bisect import bisect_left, bisect_right
from dataclasses import astuple, dataclass
from fractions import Fraction
from itertools import pairwise
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if __package__ in {None, ""}:
    sys.path.insert(0, str(ROOT))

from scripts.generate_dusart_pi_prefix import (  # noqa: E402
    POWER,
    Smooth,
    log_bound,
    smooth_powers,
)
from scripts.generate_medium_log_rows import primes_through  # noqa: E402

CUTOFF = 3594641
START = 1000
BATCH_SIZE = 256
STEP_DEPTH = 13
MODULE = "PrimeFactorUnimodality.Helpers.FiniteCertificates.DusartPublishedPiPrefix"
DESTINATION = ROOT / Path(MODULE.replace(".", "/"))
HELPER = "PrimeFactorUnimodality.Helpers.Analytic.FinitePrimeIntervalRows.PrimeCountingSieveRows"


@dataclass(frozen=True)
class Row:
    """Untrusted counts plus exact smooth-power witnesses, checked by Lean."""

    left: int
    right: int
    left_count: int
    before_count: int
    lower: Smooth
    upper: Smooth

    def margins_valid(self) -> bool:
        low = log_bound(self.lower, upper=False)
        high = log_bound(self.upper, upper=True)
        return (
            599 <= self.left < self.right <= CUTOFF + 1
            and self.lower[0] == 2 ** self.lower[1] * 3 ** self.lower[2] * 5 ** self.lower[3]
            and self.upper[0] == 2 ** self.upper[1] * 3 ** self.upper[2] * 5 ** self.upper[3]
            and self.lower[0] <= self.right**POWER
            and self.left**POWER <= self.upper[0]
            and low > 0
            and high > 0
            and self.right / low * (1 + 1 / low) <= self.left_count
            and self.before_count <= self.left / high * (1 + Fraction(6381, 5000) / high)
        )

    def valid(self, primes: list[int]) -> bool:
        return (
            self.left_count == bisect_right(primes, self.left)
            and self.before_count == bisect_right(primes, self.right - 1)
            and self.margins_valid()
        )

    def lean(self) -> str:
        def power(value: Smooth) -> str:
            return f"⟨{POWER}, {value[1]}, {value[2]}, {value[3]}⟩"

        return (
            f"⟨{self.left}, {self.right}, {self.left_count}, {self.before_count}, "
            f"{power(self.lower)}, {power(self.upper)}⟩"
        )


def certificate_rows(primes: list[int]) -> list[Row]:
    """Choose adaptive positive-width rows; no quadratic endpoint enumeration."""
    powers = smooth_powers(2 * (CUTOFF + 1) ** POWER)
    values = [power[0] for power in powers]
    rows: list[Row] = []
    left = START
    while left < CUTOFF + 1:
        upper = powers[bisect_left(values, left**POWER)]
        left_count = bisect_right(primes, left)
        width = min(CUTOFF + 1 - left, max(1, left // 250))
        while True:
            right = left + width
            lower = powers[bisect_right(values, right**POWER) - 1]
            row = Row(left, right, left_count, bisect_right(primes, right - 1), lower, upper)
            if row.margins_valid():
                break
            if width == 1:
                raise ValueError(f"no valid positive-width row at {left}")
            width = max(1, width // 2)
        rows.append(row)
        left = right
    return rows


def semantic_hash(rows: list[Row]) -> str:
    payload = [START, CUTOFF, POWER, [astuple(row) for row in rows]]
    return hashlib.sha256(json.dumps(payload, separators=(",", ":")).encode()).hexdigest()


def header(imports: str, title: str, digest: str) -> str:
    return f"""{imports}

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 0

/-! # {title}

Generated by `scripts/generate_dusart_published_pi_prefix.py`.
Semantic SHA-256: {digest}
Half-open cells retain prime jumps at their left endpoints.
-/

namespace PrimeFactorUnimodality.DusartPublishedPiPrefix

"""


def render_base(digest: str) -> str:
    return (
        header(f"import {HELPER}", "Shared published-cutoff sieve", digest)
        + """\
noncomputable def sieve : Nat := PrimeCert.Sieve.sieveK 3594641 1896

theorem sieve_valid : PrimeCert.Sieve.IsSieve 3594641 sieve :=
  PrimeCert.Sieve.isSieve_of_sieveK_eq
    (show PrimeCert.Sieve.sieveK 3594641 1896 = sieve from rfl) (by decide) (by decide)

end PrimeFactorUnimodality.DusartPublishedPiPrefix
"""
    )


def render_part(rows: list[Row], number: int, digest: str) -> str:
    previous = f"Part{number - 1:02d}" if number > 1 else "Base"
    body = header(f"import {MODULE}.{previous}", "Checked local prime-count steps", digest)
    data = ",\n    ".join(row.lean() for row in rows)
    start, stop, initial = rows[0].left, rows[-1].right, rows[0].left_count
    result = "bounds" if number == 1 else f"throughPart{number - 1:02d}.append bounds"
    return (
        body
        + f"""private def rows : List DusartHalfOpenPiRow :=
  [{data}]

private theorem initial : Nat.primeCounting {start} = {initial} :=
  primeCounting_eq_of_sieve_check sieve_valid (k := 21) (by decide +kernel)

private theorem checked :
    checkDusartSievePiSteps {CUTOFF} {STEP_DEPTH} sieve {start} {initial} rows = true := by
  decide +kernel

private theorem chain : dusartThetaTable66CellsChain {start} {stop}
    (rows.map DusartHalfOpenPiRow.coverageCell) = true := by decide +kernel

private theorem bounds : DusartHalfOpenPiBounds {start} {stop} :=
  dusartSievePiSteps_provide sieve_valid initial rows checked chain

theorem throughPart{number:02d} : DusartHalfOpenPiBounds {START} {stop} :=
  {result}

end PrimeFactorUnimodality.DusartPublishedPiPrefix
"""
    )


def render_facade(parts: int, digest: str) -> str:
    return f"""import PrimeFactorUnimodality.Helpers.Analytic.DusartPrimeCountingClosed
import {MODULE}.Part{parts:02d}

/-! # Closed prime-counting prefix through the published Dusart cutoff

Generated by `scripts/generate_dusart_published_pi_prefix.py`.
Semantic SHA-256: {digest}
The small closed prefix and half-open extension include every real input
through 3,594,641, not just integer sample points.
-/

namespace PrimeFactorUnimodality

theorem dusart_published_primeCountingPrefix :
    HasDusartRealPrimeCountingBoundsBelow {CUTOFF} :=
  hasDusartRealPrimeCountingBoundsBelow_of_halfOpen wangCrapis_primeCountingPrefix
    DusartPublishedPiPrefix.throughPart{parts:02d}

end PrimeFactorUnimodality
"""


def render_files(rows: list[Row]) -> dict[Path, str]:
    """Nine serial batches replace per-integer cases or per-prime witness files."""
    if not rows or rows[0].left != START or rows[-1].right != CUTOFF + 1:
        raise ValueError("wrong coverage endpoints")
    if any(first.right != second.left for first, second in pairwise(rows)):
        raise ValueError("nonadjacent coverage")
    digest = semantic_hash(rows)
    chunks = [rows[i : i + BATCH_SIZE] for i in range(0, len(rows), BATCH_SIZE)]
    output = {DESTINATION / "Base.lean": render_base(digest)}
    for number, chunk in enumerate(chunks, 1):
        output[DESTINATION / f"Part{number:02d}.lean"] = render_part(chunk, number, digest)
    output[DESTINATION.with_suffix(".lean")] = render_facade(len(chunks), digest)
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rows = certificate_rows(primes_through(CUTOFF))
    files = render_files(rows)
    for path, source in files.items():
        if args.check:
            if not path.exists() or path.read_text() != source:
                raise SystemExit(f"generated source differs: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(source)
    print(f"{len(rows)} rows; {len(files)} files; SHA-256 {semantic_hash(rows)}")


if __name__ == "__main__":
    main()
