"""Generate bounded theta traces from exact counts and smooth endpoint logarithms."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from bisect import bisect_left, bisect_right
from dataclasses import astuple, dataclass
from fractions import Fraction
from itertools import pairwise
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if __package__ in {None, ""}:
    sys.path.insert(0, str(ROOT))

from scripts.generate_dusart_pi_prefix import (  # noqa: E402
    POWER,
    Smooth,
    log_bound,
    smooth_powers,
)
from scripts.generate_medium_log_rows import primes_through  # noqa: E402

CUTOFF = 3594641
THRESHOLD = 3501
SIEVE_ROOT = 1896
SCALE = POWER * 1000000
WIDTH_DIVISOR = 1000
DEPTH = 11
BATCH_SIZE = 384
MODULE = "PrimeFactorUnimodality.Helpers.FiniteCertificates.DusartTailThetaPrefix"
DESTINATION = ROOT / Path(MODULE.replace(".", "/"))
HELPER = "PrimeFactorUnimodality.Helpers.Analytic.FinitePrimeIntervalRows.ThetaSieveTrace"


@dataclass(frozen=True)
class State:
    """Proposed exact count and scaled rational theta enclosure."""

    point: int
    count: int
    lower: int
    upper: int

    def lean(self) -> str:
        return f"⟨{self.point}, {self.count}, {self.lower} / {SCALE}, {self.upper} / {SCALE}⟩"


SEED = State(3, 2, 8 * (693147 + 1098612), 8 * (693148 + 1098613))


@dataclass(frozen=True)
class Row:
    """The old state is retained externally but emitted only at batch boundaries."""

    start: State
    next: State
    lower: Smooth
    upper: Smooth

    def margins_valid(self) -> bool:
        lo = log_bound(self.lower, upper=False)
        hi = log_bound(self.upper, upper=True)
        delta = self.next.count - self.start.count
        transport = (
            3 <= self.start.point < self.next.point <= CUTOFF
            and delta >= 0
            and self.lower[0] == 2 ** self.lower[1] * 3 ** self.lower[2] * 5 ** self.lower[3]
            and self.upper[0] == 2 ** self.upper[1] * 3 ** self.upper[2] * 5 ** self.upper[3]
            and self.lower[0] <= self.start.point**POWER
            and self.next.point**POWER <= self.upper[0]
            and self.next.lower <= self.start.lower + delta * lo * SCALE
            and self.start.upper + delta * hi * SCALE <= self.next.upper
        )
        if self.next.point <= THRESHOLD:
            return transport
        return (
            transport
            and Fraction(12323, 10000) <= hi
            and Fraction(self.next.upper, SCALE) < Fraction(1001 * self.start.point, 1000)
            and self.next.point * (1 - Fraction(12323, 10000) / hi)
            < Fraction(self.start.lower, SCALE)
        )

    def valid(self, primes: list[int]) -> bool:
        return (
            self.start.count == bisect_right(primes, self.start.point)
            and self.next.count == bisect_right(primes, self.next.point)
            and self.margins_valid()
        )

    def lean(self) -> str:
        def power(value: Smooth) -> str:
            return f"⟨{POWER}, {value[1]}, {value[2]}, {value[3]}⟩"

        return f"⟨{self.next.lean()},\n      {power(self.lower)}, {power(self.upper)}⟩"


def certificate_rows(primes: list[int]) -> list[Row]:
    powers = smooth_powers(2 * CUTOFF**POWER)
    values = [power[0] for power in powers]
    rows: list[Row] = []
    start = SEED
    while start.point < CUTOFF:
        point = min(CUTOFF, start.point + max(1, start.point // WIDTH_DIVISOR))
        if start.point < THRESHOLD:
            point = min(point, THRESHOLD)
        lower = powers[bisect_right(values, start.point**POWER) - 1]
        upper = powers[bisect_left(values, point**POWER)]
        count = bisect_right(primes, point)
        delta = count - start.count
        low = log_bound(lower, upper=False) * SCALE
        high = log_bound(upper, upper=True) * SCALE
        if low.denominator != 1 or high.denominator != 1:
            raise ValueError("logarithm coefficients exceed the exact scale")
        end = State(point, count, start.lower + delta * int(low), start.upper + delta * int(high))
        row = Row(start, end, lower, upper)
        if not row.margins_valid():
            raise ValueError(f"failed transport or strict tail margin at {start.point}")
        rows.append(row)
        start = end
    return rows


def semantic_hash(rows: list[Row]) -> str:
    payload = [
        CUTOFF,
        THRESHOLD,
        SCALE,
        DEPTH,
        SIEVE_ROOT,
        astuple(SEED),
        [astuple(row) for row in rows],
    ]
    return hashlib.sha256(json.dumps(payload, separators=(",", ":")).encode()).hexdigest()


def header(imports: str, title: str, digest: str) -> str:
    return f"""{imports}

set_option autoImplicit false
set_option maxRecDepth 100000

/-! # {title}

Generated by `scripts/generate_dusart_tail_theta_prefix.py`.
Semantic SHA-256: {digest}
Only the data in this replay unit contributes to its semantic digest.
-/

namespace PrimeFactorUnimodality.DusartTailThetaPrefix

"""


def render_base() -> str:
    return (
        header(f"import {HELPER}", "Shared theta-prefix sieve", semantic_hash([]))
        + f"""\
noncomputable def sieve : Nat := PrimeCert.Sieve.sieveK {CUTOFF} {SIEVE_ROOT}

theorem sieve_valid : PrimeCert.Sieve.IsSieve {CUTOFF} sieve :=
  PrimeCert.Sieve.isSieve_of_sieveK_eq
    (show PrimeCert.Sieve.sieveK {CUTOFF} {SIEVE_ROOT} = sieve from rfl)
    (by decide) (by decide)

end PrimeFactorUnimodality.DusartTailThetaPrefix
"""
    )


def render_part(rows: list[Row], number: int) -> str:
    previous = f"Part{number - 1:02d}" if number > 1 else "Base"
    start = f"state{number - 1:02d}" if number > 1 else "dusartThetaSeed"
    valid = f"state{number - 1:02d}_valid" if number > 1 else "dusartThetaSeed_valid"
    result = "result.2" if number == 1 else f"throughPart{number - 1:02d}.append result.2"
    body = header(f"import {MODULE}.{previous}", "Checked theta trace batch", semantic_hash(rows))
    data = ",\n    ".join(row.lean() for row in rows)
    return (
        body
        + f"""private def rows : List DusartThetaSieveStep :=
  [{data}]

def state{number:02d} : DusartThetaState :=
  {rows[-1].next.lean()}

set_option maxHeartbeats 0 in
-- Kernel reduction checks the bounded trace and its exact final state.
private theorem checked :
    checkDusartThetaTrace {CUTOFF} {DEPTH} sieve {start} state{number:02d} rows = true := by
  decide +kernel

private theorem result : state{number:02d}.Valid ∧
    DusartTailThetaSegment {start}.point state{number:02d}.point :=
  checkDusartThetaTrace_sound sieve_valid {valid} checked

theorem state{number:02d}_valid : state{number:02d}.Valid := result.1

theorem throughPart{number:02d} : DusartTailThetaSegment 3 {rows[-1].next.point} :=
  {result}

end PrimeFactorUnimodality.DusartTailThetaPrefix
"""
    )


def render_facade(parts: int, digest: str) -> str:
    return f"""import {MODULE}.Part{parts:02d}

/-! # Closed finite theta prefix for the all-k tail

Generated by `scripts/generate_dusart_tail_theta_prefix.py`.
Semantic SHA-256: {digest}
All endpoint counts, accumulated logarithm sums and strict margins are checked.
-/

namespace PrimeFactorUnimodality

theorem dusart_tail_theta_prefix (q : Nat) (hq : 3501 ≤ q) (hcut : q < {CUTOFF}) :
    TailThetaAt q :=
  DusartTailThetaPrefix.throughPart{parts:02d} q hq (by omega) hcut

end PrimeFactorUnimodality
"""


def render_files(rows: list[Row]) -> dict[Path, str]:
    if not rows or rows[0].start != SEED or rows[-1].next.point != CUTOFF:
        raise ValueError("wrong trace endpoints")
    if any(first.next != second.start for first, second in pairwise(rows)):
        raise ValueError("nonadjacent checkpoint states")
    chunks = [rows[i : i + BATCH_SIZE] for i in range(0, len(rows), BATCH_SIZE)]
    output = {DESTINATION / "Base.lean": render_base()}
    for number, chunk in enumerate(chunks, 1):
        output[DESTINATION / f"Part{number:02d}.lean"] = render_part(chunk, number)
    output[DESTINATION.with_suffix(".lean")] = render_facade(len(chunks), semantic_hash(rows))
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rows = certificate_rows(primes_through(CUTOFF))
    files = render_files(rows)
    for path, source in files.items():
        if args.check:
            if not path.exists() or path.read_text() != source:
                raise SystemExit(f"generated source differs: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(source)
    print(f"{len(rows)} rows; {len(files)} files; SHA-256 {semantic_hash(rows)}")


if __name__ == "__main__":
    main()
