"""Generate shared-prime-list certificates for the Dusart prefix through 1000."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from bisect import bisect_left, bisect_right
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if __package__ in {None, ""}:
    sys.path.insert(0, str(ROOT))

from scripts.generate_medium_log_rows import primes_through  # noqa: E402

DESTINATION = (
    ROOT / "PrimeFactorUnimodality/Helpers/FiniteCertificates/DusartPrimeCountingPrefix.lean"
)
POWER = 8
Smooth = tuple[int, int, int, int]
Row = tuple[int, int, Smooth, Smooth]


def smooth_powers(limit: int) -> list[Smooth]:
    """Enumerate exact integers; floating-point logarithms are not used."""
    result: list[Smooth] = []
    a, two = 0, 1
    while two <= limit:
        b, three = 0, two
        while three <= limit:
            c, value = 0, three
            while value <= limit:
                result.append((value, a, b, c))
                c, value = c + 1, value * 5
            b, three = b + 1, three * 3
        a, two = a + 1, two * 2
    return sorted(result)


def log_bound(power: Smooth, *, upper: bool) -> Fraction:
    """The coefficients are the enclosures proved by PrimeCountingLogBounds."""
    _, a, b, c = power
    delta = int(upper)
    return Fraction(
        a * (693147 + delta) + b * (1098612 + delta) + c * (1609437 + delta),
        POWER * 1000000,
    )


def row_valid(row: Row, primes: list[int]) -> bool:
    left, right, lower, upper = row
    low_log = log_bound(lower, upper=False)
    high_log = log_bound(upper, upper=True)
    return (
        599 <= left <= right <= 1000
        and lower[0] == 2 ** lower[1] * 3 ** lower[2] * 5 ** lower[3]
        and upper[0] == 2 ** upper[1] * 3 ** upper[2] * 5 ** upper[3]
        and lower[0] <= right**POWER
        and left**POWER <= upper[0]
        and low_log > 0
        and high_log > 0
        and right / low_log * (1 + 1 / low_log) <= bisect_right(primes, left)
        and bisect_right(primes, right) <= left / high_log * (1 + Fraction(6381, 5000) / high_log)
    )


def certificate_rows(primes: list[int]) -> list[Row]:
    powers = smooth_powers(2 * 1000**POWER)
    values = [power[0] for power in powers]
    lowers = {n: powers[bisect_right(values, n**POWER) - 1] for n in range(599, 1001)}
    uppers = {n: powers[bisect_left(values, n**POWER)] for n in range(599, 1001)}
    rows: list[Row] = []
    left = 599
    while left < 1000:
        candidates = [
            (left, right, lowers[right], uppers[left])
            for right in range(left + 1, 1001)
            if row_valid((left, right, lowers[right], uppers[left]), primes)
        ]
        if not candidates:
            raise ValueError(f"no positive-width checked row starting at {left}")
        chosen = candidates[-1]
        rows.append(chosen)
        left = chosen[1]
    return rows


def render(*, one_row: bool = False) -> str:
    primes = primes_through(1000)
    rows = certificate_rows(primes)
    if one_row:
        rows = rows[:1]
    end = rows[-1][1]
    digest = hashlib.sha256(json.dumps([primes, rows], separators=(",", ":")).encode()).hexdigest()
    prime_lines = [", ".join(map(str, primes[i : i + 12])) for i in range(0, len(primes), 12)]
    rendered_primes = ",\n    ".join(prime_lines)
    rendered_rows = ",\n    ".join(
        f"⟨{left}, {right}, ⟨{POWER}, {lower[1]}, {lower[2]}, {lower[3]}⟩, "
        f"⟨{POWER}, {upper[1]}, {upper[2]}, {upper[3]}⟩⟩"
        for left, right, lower, upper in rows
    )
    module = (
        "PrimeFactorUnimodality.Helpers.Analytic.FinitePrimeIntervalRows.PrimeCountingCertificates"
    )
    return f"""import {module}

set_option autoImplicit false
set_option maxRecDepth 10000

/-! # Shared prime-counting prefix certificate

Generated by `scripts/generate_dusart_pi_prefix.py`.
Semantic SHA-256: {digest}
One prime list supplies all {len(rows)} rational endpoint rows.
-/

namespace PrimeFactorUnimodality

def dusartPrimesThrough1000 : List Nat :=
  [{rendered_primes}]

theorem dusartPrimesThrough1000_eq :
    computablePrimesBelow 1001 = dusartPrimesThrough1000 := by
  decide +kernel

theorem dusart_primeCounting_eq_filtered_1000 {{n : Nat}} (hn : n ≤ 1000) :
    Nat.primeCounting n = dusartPrefixCount dusartPrimesThrough1000 n :=
  primeCounting_eq_filter_length_of_prime_prefix hn dusartPrimesThrough1000_eq

def dusartPrimeCountingCertificateRows599_{end} : List DusartPrimeCountingCertificateRow :=
  [{rendered_rows}]

private theorem certificate_valid :
    dusartPrimeCountingCertificateRows599_{end}.all
      (fun row => row.check 1000 dusartPrimesThrough1000) = true := by
  decide +kernel

private theorem certificate_chain :
    dusartThetaTable66CellsChain 599 {end}
      (dusartPrimeCountingCertificateRows599_{end}.map
        DusartPrimeCountingCertificateRow.coverageCell) = true := by
  decide +kernel

theorem dusartPrimeCounting_599_{end} :
    ∀ x : Real, 599 ≤ x → x ≤ {end} →
      dusartPiLower x ≤ (Nat.primeCounting ⌊x⌋₊ : Real) ∧
        (Nat.primeCounting ⌊x⌋₊ : Real) ≤ dusartPiUpper x :=
  dusartPrimeCountingCertificateRows_provide dusartPrimesThrough1000_eq
    dusartPrimeCountingCertificateRows599_{end} certificate_valid certificate_chain

end PrimeFactorUnimodality
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DESTINATION)
    parser.add_argument("--one-row", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render(one_row=args.one_row)
    if args.check:
        if args.output.read_text() != content:
            raise SystemExit(f"generated certificate differs: {args.output}")
    else:
        args.output.write_text(content)


if __name__ == "__main__":
    main()
