"""Generate compact sieve/log rows for the complete published short-interval prefix."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from bisect import bisect_left, bisect_right
from dataclasses import astuple, dataclass
from itertools import pairwise
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if __package__ in {None, ""}:
    sys.path.insert(0, str(ROOT))

from scripts.generate_dusart_pi_prefix import (  # noqa: E402
    POWER,
    Smooth,
    log_bound,
    smooth_powers,
)
from scripts.generate_medium_log_rows import primes_through  # noqa: E402

START = 3275
CUTOFF = 3594641
SIEVE_LIMIT = 4000000
SIEVE_ROOT = 2000
BATCH_SIZE = 256
MODULE = "PrimeFactorUnimodality.Helpers.FiniteCertificates.DusartPublishedShortPrefix"
DESTINATION = ROOT / Path(MODULE.replace(".", "/"))
HELPER = "PrimeFactorUnimodality.Helpers.Analytic.FinitePrimeIntervalRows.ShortIntervalSieveRows"


@dataclass(frozen=True)
class Row:
    """One proposed witness prime covers the entire half-open cell on its left."""

    left: int
    prime: int
    index: int
    power: Smooth

    def margins_valid(self) -> bool:
        bound = log_bound(self.power, upper=True)
        return (
            START <= self.left < self.prime <= SIEVE_LIMIT
            and min(self.power[1:]) >= 0
            and self.power[0] == 2 ** self.power[1] * 3 ** self.power[2] * 5 ** self.power[3]
            and self.prime**POWER <= self.power[0]
            and bound > 0
            and (self.prime - self.left) * 2 * bound**2 <= self.left
        )

    def valid(self, primes: set[int]) -> bool:
        return self.prime in primes and self.index == (self.prime - 1) // 3 and self.margins_valid()

    def lean(self) -> str:
        return (
            f"⟨{self.left}, {self.prime}, {self.index}, "
            f"⟨{POWER}, {self.power[1]}, {self.power[2]}, {self.power[3]}⟩⟩"
        )


def certificate_rows(primes: list[int]) -> list[Row]:
    """Choose a distant witness, then enforce the exact upper-log width comparison."""
    powers = smooth_powers(2 * SIEVE_LIMIT**POWER)
    values = [power[0] for power in powers]
    rows: list[Row] = []
    left = START
    while left <= CUTOFF:
        bound = log_bound(powers[bisect_left(values, left**POWER)], upper=True)
        index = bisect_right(primes, left + int(left / (2 * bound**2))) - 1
        while True:
            prime = primes[index]
            if prime <= left:
                raise ValueError(f"no valid witness after {left}")
            power = powers[bisect_left(values, prime**POWER)]
            row = Row(left, prime, (prime - 1) // 3, power)
            if row.margins_valid():
                break
            index -= 1
        rows.append(row)
        left = prime
    return rows


def semantic_hash(rows: list[Row]) -> str:
    payload = [START, CUTOFF, SIEVE_LIMIT, SIEVE_ROOT, POWER, [astuple(row) for row in rows]]
    return hashlib.sha256(json.dumps(payload, separators=(",", ":")).encode()).hexdigest()


def header(imports: str, title: str, digest: str) -> str:
    return f"""{imports}

set_option autoImplicit false
set_option maxRecDepth 100000

/-! # {title}

Generated by `scripts/generate_dusart_published_short_prefix.py`.
Semantic SHA-256: {digest}
Strict prime endpoints are included in the following cell.
-/

namespace PrimeFactorUnimodality.DusartPublishedShortPrefix

"""


def render_base(digest: str) -> str:
    return (
        header(f"import {HELPER}", "Shared short-interval sieve", digest)
        + f"""\
noncomputable def sieve : Nat := PrimeCert.Sieve.sieveK {SIEVE_LIMIT} {SIEVE_ROOT}

theorem sieve_valid : PrimeCert.Sieve.IsSieve {SIEVE_LIMIT} sieve :=
  PrimeCert.Sieve.isSieve_of_sieveK_eq
    (show PrimeCert.Sieve.sieveK {SIEVE_LIMIT} {SIEVE_ROOT} = sieve from rfl)
    (by decide) (by decide)

end PrimeFactorUnimodality.DusartPublishedShortPrefix
"""
    )


def render_part(rows: list[Row], number: int, digest: str) -> str:
    previous = f"Part{number - 1:02d}" if number > 1 else "Base"
    body = header(f"import {MODULE}.{previous}", "Checked short-interval witness rows", digest)
    data = ",\n    ".join(row.lean() for row in rows)
    start, stop = rows[0].left, rows[-1].prime
    result = "bounds" if number == 1 else f"throughPart{number - 1:02d}.append bounds"
    return (
        body
        + f"""private def rows : List DusartShortSieveRow :=
  [{data}]

set_option maxHeartbeats 0 in
-- The bounded batch is checked by kernel reduction.
private theorem checked : rows.all (fun row => row.check {SIEVE_LIMIT} sieve) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- Coverage is checked separately from the arithmetic.
private theorem chain : dusartThetaTable66CellsChain {start} {stop}
    (rows.map DusartShortSieveRow.coverageCell) = true := by decide +kernel

private theorem bounds : DusartHalfOpenShortBounds {start} {stop} :=
  dusartShortSieveRows_provide sieve_valid rows checked chain

theorem throughPart{number:02d} : DusartHalfOpenShortBounds {START} {stop} :=
  {result}

end PrimeFactorUnimodality.DusartPublishedShortPrefix
"""
    )


def render_facade(parts: int, stop: int, digest: str) -> str:
    return f"""import {MODULE}.Part{parts:02d}

/-! # Closed short-interval prefix through the published Dusart cutoff

Generated by `scripts/generate_dusart_published_short_prefix.py`.
Semantic SHA-256: {digest}
The half-open cover includes every real input through 3,594,641.
-/

namespace PrimeFactorUnimodality

theorem dusart_published_shortIntervalPrefix :
    HasDusartShortIntervalPrimeBelow {CUTOFF} :=
  hasDusartShortIntervalPrimeBelow_of_halfOpen (by decide : {CUTOFF} < {stop})
    DusartPublishedShortPrefix.throughPart{parts:02d}

end PrimeFactorUnimodality
"""


def render_files(rows: list[Row]) -> dict[Path, str]:
    if not rows or rows[0].left != START or rows[-1].left > CUTOFF:
        raise ValueError("wrong coverage endpoints")
    if rows[-1].prime <= CUTOFF:
        raise ValueError("cutoff not covered")
    if any(first.prime != second.left for first, second in pairwise(rows)):
        raise ValueError("nonadjacent coverage")
    digest = semantic_hash(rows)
    chunks = [rows[i : i + BATCH_SIZE] for i in range(0, len(rows), BATCH_SIZE)]
    output = {DESTINATION / "Base.lean": render_base(digest)}
    for number, chunk in enumerate(chunks, 1):
        output[DESTINATION / f"Part{number:02d}.lean"] = render_part(chunk, number, digest)
    output[DESTINATION.with_suffix(".lean")] = render_facade(len(chunks), rows[-1].prime, digest)
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rows = certificate_rows(primes_through(SIEVE_LIMIT))
    files = render_files(rows)
    for path, source in files.items():
        if args.check:
            if not path.exists() or path.read_text() != source:
                raise SystemExit(f"generated source differs: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(source)
    print(f"{len(rows)} rows; {len(files)} files; SHA-256 {semantic_hash(rows)}")


if __name__ == "__main__":
    main()
